name: Test CI/CD

on:
  pull_request:
    types:
      - closed
    branches:
      - development

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Uncomment if linting is required
      # - name: Lint code
      #   run: npm run lint

      - name: Run unit tests
        run: npm test -- --coverage

      - name: Build project
        run: npm run build

      - name: Create PR to production
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            const prTitle = `Merge development into production`;
            const prBody = `Automated PR to merge changes from development to production.`;
            const baseBranch = 'production';
            const headBranch = 'development';
            const result = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: prTitle,
              body: prBody,
              head: headBranch,
              base: baseBranch,
            });
            console.log(result.data.html_url);
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
